# Generated by Django 5.0.6 on 2024-06-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predicciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temperatura', models.FloatField()),
                ('Valor_Prediccion', models.FloatField()),
                ('RMSE', models.FloatField()),
                ('MAPE', models.FloatField()),
                ('Modelo', models.CharField(max_length=100)),
                ('DS', models.CharField(max_length=1)),
                ('VAR', models.CharField(max_length=100)),
                ('NVAR', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
